# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: OpenG2P
org_slug: OpenG2P
rebel_module_groups: []
repo_description: The repo contains modules that connect OpenG2P with MOSIP Token
    Seeder(MTS) to seed MOSIP Tokens of the registrants
repo_name: OpenG2P Registry MTS Connector
repo_slug: openg2p-mts
repo_website: https://github.com/OpenG2P/openg2p-mts
travis_apt_packages: []
travis_apt_sources: []

